console.dir(document);

// CRUD

// Read

// const parentEl = document.getElementById("parent")
// const pEl = document.getElementById("p")
// const  btn = document.getElementById("btn")
// Create

// const newEl = document.createElement("h2")

// newEl.textContent = "This is Generated by Js"

// parentEl.insertBefore(newEl,pEl)


// Update

// pEl.textContent = "new updated "

// pEl.style.color="red"
// pEl.style.fontSize="40px"




// Delete

// btn.remove()




// Events

// click, mousehover ,

// AddEventlistners



// const parentEl = document.getElementById("parent")
// const pEl = document.getElementById("p")
// const  btn = document.getElementById("btn")



// btn.addEventListener("mouseover",()=>{
//     pEl.style.color="red"
//     pEl.textContent = "YAYYYY"
// })





// How does eventlistners work ?

const itemList = document.getElementById('itemList');
const addItemButton = document.getElementById('addItemButton');



itemList.style.border = "1px solid red"

itemList.addEventListener('click', function(event) {
  if (event.target && event.target.matches('.item')) {
    alert(`You clicked on ${event.target.textContent}`);
  }
});

function addItem() {
    const newItem = document.createElement('li');
    newItem.className = 'item';
    newItem.textContent = `Item value`;
    itemList.querySelector('ul').appendChild(newItem);
}

addItemButton.addEventListener('click', () => {
  addItem();
});
//   Bubbling up